---
title: "Stonks Visualization"
output: html_notebook
---

```{r}
library(tidyverse)
library(lubridate)
library(tidyverse)
library(ggplot2)
library(gifski)
library(png)
library(gganimate)
library(gapminder)
```


### The project {.tabset}

This data was collected in a mock crypto currency competition at Saint Thomas University.


<br>

**Exploring the data**


```{r}
Crypto_Hackathon_stonks
```


**Creating New Coluns**


```{r}


Crypto_Hackathon_stonks$day <- mdy_hm(Crypto_Hackathon_stonks$date)


Crypto_Hackathon_stonks
  
  
```

#### stonk data

```{r}
stonk <- Crypto_Hackathon_stonks
stonk
```

```{r}
stonk$hour <- hour(stonk$day)
stonk$day <- day(stonk$day)
stonk$minu <- format(stonk$day, format = "%M")

stonk$date <- format(stonk$day, format = "%Y-%m-%d")
stonk
```







#### Variables over the time




```{r}
stonks_longer <- Crypto_Hackathon_stonks %>% select(total, penalty,
                                                     cash, day)

```


```{r}
stonks_longer <- pivot_longer(stonks_longer, cols = total:cash,
                              names_to = "Type",
                              values_to = "Dollar_Amount")
```

```{r}
stonks_longer
```


```{r}
ggplot(stonks_longer, mapping = aes(x = Dollar_Amount, y  = factor(Type))) +
  geom_col(mapping = aes(fill = Type), position = "dodge") + 
  transition_time(day) +
  ease_aes("linear") + 
  labs(title = "Amount of Big Data Dollars over the Time",
       subtitle = "Filtered by Type",
       caption = "Source: Crypto CUrrency Copetition",
       y = "type")
  
```

#### "Penalty for Crypto_Hackathon Stonks Team in the period"



```{r}
pen <- ggplot(stonk, aes(x = penalty, fill = day)) +
  geom_histogram()+
  labs(title = "Penalty for Crypto_Hackathon Stonks Team in the period",
       subtitle = "Crypto_Hackathon_stonks",
       x = "Penalty",
       y = "Day",
       caption = "Source: Dr. Mondesire") +
  transition_states(
  total,
  transition_length = 4,
  state_length = 4) +
  enter_fade() +
  exit_shrink() +
  ease_aes('sine-in-out')

pen
```




#### Cash by Minutes for Crypto_Hackathon Stonks Team


```{r}
cas <- ggplot(stonk, aes(minu, cash)) +
  geom_point()+geom_line()+
  labs(title = "Cash by Minutes for Crypto_Hackathon Stonks Team",
       subtitle = "Crypto_Hackathon_stonks",
       x = "Minutes ",
       y = "Cash",
       caption = "Source: Dr. Mondesire") +
  theme_minimal() +
  transition_reveal(total)
  
cas
```







#### Penaties by Hour for Crypto_Hackathon Stonks Team


```{r}
fig3 <- ggplot(stonk, aes(hour, penalty)) +
  geom_point()+geom_line() +
  labs(title = "Penaties by Hour for Crypto_Hackathon Stonks Team",
       subtitle = "Crypto_Hackathon_Stonks",
       x = "Hour",
       y = "Penalty", caption = "Source: Dr. Mondesire") +
  theme_minimal() +
  transition_reveal(total, range = NULL, keep_last = TRUE)
fig3
```


